"""initial schema: user, poll, vote

Hand-written rather than autogenerated so the first revision is reviewable and
reproducible. It must stay in step with app/models.py.

This revision deliberately reproduces the schema exactly as the old
`db.create_all()` emitted it -- no `is_admin`, no `ix_vote_poll_choice`. That
matters for the upgrade path: a volume created before migrations existed already
has this schema, so the entrypoint can stamp *this* revision and let 0002 add
what is missing, instead of stamping head and leaving the app against a stale
table.

Why migrations at all: `db.create_all()` never ALTERs an existing table, so any
future column or index change would be silently ignored on any deployment whose
`postgres_data` volume already existed. `flask db upgrade` runs from
app/entrypoint.sh on every boot.

Revision ID: 0001
Revises:
Create Date: 2026-10-05

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        # The unique constraint is what makes concurrent registrations resolvable:
        # both requests pass the pre-check and only the loser is caught here.
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )

    op.create_table(
        'poll',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.String(length=255), nullable=False),
        sa.Column('option_a', sa.String(length=100), nullable=False),
        sa.Column('option_b', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'vote',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('poll_id', sa.Integer(), nullable=False),
        sa.Column('choice', sa.String(length=1), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        # Final backstop for one-vote-per-user. The app gates on an atomic Redis
        # SADD and the worker treats a violation as a no-op, so this constraint
        # only fires if something bypassed both -- which is what it is for.
        sa.UniqueConstraint('user_id', 'poll_id', name='_user_poll_uc'),
        sa.ForeignKeyConstraint(['poll_id'], ['poll.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
    )


def downgrade():
    op.drop_table('vote')
    op.drop_table('poll')
    op.drop_table('user')
